package sh.ondr.kojas.ksp

import com.google.devtools.ksp.processing.Dependencies

fun KojasProcessor.generateInitializer() {
	val name = "${moduleName?.getQualifier()}KojaInitializer"
	val file = codeGenerator.createNewFile(
		dependencies = Dependencies(
			aggregating = true,
			sources = originatingFiles.toTypedArray(),
		),
		packageName = kojasInitializerPackage,
		fileName = name,
	)

	val code = buildString {
		appendLine("// Generated by kojas")
		appendLine("package $kojasInitializerPackage")
		appendLine()
		appendLine("object $name {")
		appendLine("  init {")
		generatedMetasFqs.forEach { fq ->
			appendLine("  sh.ondr.kojas.KojasRegistry.map[$fq.first] = $fq.second")
		}
		appendLine("  }")
		appendLine("}")
	}

	file.write(code.toByteArray())
	file.close()
}
