package sh.ondr.koja.ksp

import com.google.devtools.ksp.processing.Dependencies

fun KojaProcessor.generateInitializer() {
	val objectName = "KojaInitializer_$moduleId"
	val file = codeGenerator.createNewFile(
		dependencies = Dependencies(
			aggregating = false,
		),
		packageName = kojaInitializerPackage,
		fileName = objectName,
	)

	val code = buildString {
		appendLine("// Generated by Koja")
		appendLine("package $kojaInitializerPackage")
		appendLine()
		appendLine("object $objectName {")
		appendLine("  init {")
		if (isTest) {
			val mainObjectName = "KojaInitializer_${moduleId!!.removeSuffix("_test")}"
			appendLine("    $mainObjectName.toString()")
		}
		generatedMetasFqs
			.sorted()
			.forEach { fq ->
				appendLine("    sh.ondr.koja.KojaRegistry.map[$fq.first] = $fq.second")
			}
		appendLine("  }")
		appendLine("}")
	}

	file.write(code.toByteArray())
	file.close()
}
