package sh.ondr.koja.ksp

import com.google.devtools.ksp.processing.Dependencies

fun KojaProcessor.generateInitializer() {
	val name = "${moduleName?.getQualifier()}KojaInitializer"
	val file = codeGenerator.createNewFile(
		dependencies = Dependencies(
			aggregating = true,
			sources = originatingFiles.toTypedArray(),
		),
		packageName = kojaInitializerPackage,
		fileName = name,
	)

	val code = buildString {
		appendLine("// Generated by Koja")
		appendLine("package $kojaInitializerPackage")
		appendLine()
		appendLine("object $name {")
		appendLine("  init {")
		generatedMetasFqs.forEach { fq ->
			appendLine("    sh.ondr.koja.KojaRegistry.map[$fq.first] = $fq.second")
		}
		appendLine("  }")
		appendLine("}")
	}

	file.write(code.toByteArray())
	file.close()
}
