name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (build only, no publishing)'
        required: false
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  publish:
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Install MinGW toolchain
        run: |
          brew update && brew install mingw-w64
          echo "$(brew --prefix)/opt/mingw-w64/bin" >> $GITHUB_PATH

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: on-failure

      - name: Cache Kotlin/Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
            ~/.gradle/kotlin
          key: ${{ runner.os }}-konan-${{ hashFiles('gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Build all targets (dry run)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run }}
        run: |
          echo "🔨 DRY RUN: Building all targets without publishing..."
          ./gradlew build --no-daemon --stacktrace --parallel --build-cache
          
          echo "📦 Would publish these artifacts:"
          ./gradlew :koja-runtime:publishToMavenLocal :koja-ksp:publishToMavenLocal :koja-compiler:publishToMavenLocal :koja-gradle:publishToMavenLocal --dry-run

      - name: Publish to Maven Central
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && !inputs.dry_run) }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ./gradlew \
            publishAndReleaseToMavenCentral \
            --no-daemon --stacktrace --parallel --build-cache